#!/usr/bin/env ruby
#
# Remove first $1 rows and last $2 rows from stdin.
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

pos = 0
start = ARGV[0].to_i
eend = ARGV[1].to_i + start
lines = []

while line=STDIN.gets
	if pos > start
		lines << line
	end
	if pos > eend
		print lines.shift
	end
	pos += 1
end

