#!/usr/bin/env bash
#
# Check a list of passwords against encfs.
# If you forgot your exact password but have an list of possible passwords you can use this to check if one of them is correct.
#
# Example:
#   brute-encfs /path/to/encfs.enc /path/to/my/passwords.txt
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

if [ $# -lt 1 ]
then
  echo "usage:" "$0" "<folder.enc> <wordlist>"
  exit 1
fi

file=$1
wordlist=$2

IFS=$'\n'
i=0
offset=0

mkdir -p /tmp/brute-enc-target

while read -u 10 line
do
  let i=i+1
  if [ $offset -gt $i ]
  then
    continue
  fi

  echo "$i"
  (echo "$line" | encfs "$file" /tmp/brute-enc-target --stdinpass )\
    && (echo found password: "$line" | tee -a /tmp/brute) \
    && exit 0
done 10< $wordlist

echo "No password found"
exit 1
