#!/usr/bin/env ruby
#
# Show a gtk color picker and print color value to stdout.
#
# Example:
#   ./color-picker
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

require 'gtk3'

class RubyApp < Gtk::Window

  def initialize
    super

    dialog = Gtk::ColorSelectionDialog.new title: "Select a color"
    response = dialog.run

    if response == Gtk::ResponseType::OK
      puts to_hex dialog.color_selection.current_rgba
      dialog.destroy
      exit 0
    end
    exit 1
  end
end

def to_hex col
  # add .1 to catch decimal/dual conversion errors
  "#%02X%02X%02X" % [col.red*255.1, col.green*255.1, col.blue*255.1]
end

Gtk.init
RubyApp.new
