#!/bin/bash
#
# Encfs helper
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

if ( mount | grep "${PWD}/enc" )
then
  fusermount -u "${PWD}/enc"
else
  encfs "${PWD}/.enc" "${PWD}/enc"
fi

