#!/bin/bash
#
# Return exit code $1 or 1 if $1 is not a number
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

if [[ "$1" =~ ^[0-9]+$ ]]
then
  exit "$1"
else
  exit 1
fi

