#!/bin/sh
#
# Copy tracks from a garmin gps unit.
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

DESTINATION=~/data/gps/tracks

hash=`date +%Y-%m-%d_%H-%M-%S.gpx`

mkdir -p $DESTINATION || (echo "Cannot create file: $DESTINATION" && exit 1)

echo "gpsbabel -t -i garmin -f /dev/ttyUSB0 -o gpx -F $DESTINATION/$hash"
gpsbabel -t -i garmin -f /dev/ttyUSB0 -o gpx -F $DESTINATION/$hash || exit $?
echo done!

