#!/usr/bin/env bash
#
# Invert the exit code of a program.
#
# Example:
#   while not ./connect.sh ; do sleep 5 ; done
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##
if "$@"
then
  exit 1
else
  exit 0
fi
