#!/usr/bin/env ruby

@words = File.read("/tmp/words").split("\nNEXTWORD\n")
@words = @words.map{|x| x.split("\n")}

@max = @words.length-1
shuffle = false


def print_ordered pre="", i=0
  @words[i].each do |word|
    if i == @max
      puts pre + word
    else
      print_ordered(pre+word, i+1)
    end
  end
end


def get pre, pos
  if pos > 1
    @words[i].each do |word|
      get(pre + word, pos - 1)
    end
  else
    @words.each do |word|
      puts pre + word
    end
  end
end

print_ordered
