#!/usr/bin/env bash
#
# Print a qr code inside the terminal
# Requires https://github.com/qsantos/qrcode
#
# Example:
#   qr "some data"
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

data="$1"

echo
echo
qrcode -e "$data" \
  | sed "s/1 */██/g" \
  | sed "s/0 */  /g" \
  | grep -v 2 \
  | grep -v P \
  | sed "s/^/    /"

echo
