#!/bin/bash
#
# Retry a command until it succeeds
#
# example:
#   retry 10 ./connect.sh  # run connect script, timeout after 10 seconds and try again
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

RETRIES=1000

if [ $# -lt 1 ]
then
  echo "usage:" "$0" "[timeout-per-attempt] command"
  exit 1
fi

i=0
c=1

while not exit-code $c
do
  [ $i -gt $RETRIES ] && exit $c
  [ $i -gt 0 ] && sleep .3
  let i+=1

  echo
  echo "> try:" "$@"
  echo

  if [[ "$1" =~ ^[0-9]+$ ]]
  then
    timeout "$@" || c=$? && echo "> FAILED ($c)"
  else
    "$@" || c=$? && echo "> FAILED ($c)"
  fi
done
