#!/bin/bash
#
# Script to suspend to ram and lock screen.
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

# one second to cancel
sleep 1

# lock and suspend
slock & sudo s2ram

