#!/usr/bin/env bash
#
# Scan a A4 page with incrementing index
#
# Example:
#   scan my-document   # will save as my-document.p1.jpg
#   scan my-document   # will save as my-document.p2.jpg
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

set -euo pipefail

if [ $# -lt 1 ]
then
  echo "usage:" "$0" "<prefix> # will create <prefix>.p<i>.jpg"
  exit 1
fi

prefix="$1"
i=1

while true
do
  file="$prefix.p$i.jpg"
  ls "$file" > /dev/null 2> /dev/null || break
  let i="$i + 1"
done

echo "Scanning $file"

scanimage -d plustek:libusb:$(lsusb | grep -i scan | head -n 1 | sed "s/Bus.\([0-9]*\).Device.\([0-9]*\).*/\1:\2/") -x 215 -y 297 --format=jpeg --resolution=300 \
  | convert - -quality 50 "$file"
