#!/bin/bash
#
# Edit daily log file
#
# usage: today [offset] [postfix]
#
# example:
#   today
#   today -2
#   today projects
#   today -1 projects
#   today 2013-11-27
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

days="$1"
postfix="$2"
unit="days"

[[ "$1" =~ ^[0-9\.-]+$ ]] || days=0
[[ "$1" =~ ^[0-9\.-]+$ ]] || postfix="$1"
[[ "$days" =~ [0-9][\.-] ]] && unit=""
[[ "$postfix" == "" ]] || postfix=".$postfix"

file="$TODAY_LOG_PATH/`date -d "$days $unit 12:00" +%Y/%m/%d`$postfix"

cd "$TODAY_LOG_PATH"

case "$1" in
  "ls"|"list")
    tree
    ;;
  "commit")
    git add . \
      && git commit -v \
      && git push
    ;;
  "push")
    git push
    ;;
  *)
    mkdir -p `dirname $file` \
      && vim "$file" \
      && wq
    ;;
esac

exit $?
