#!/usr/bin/env bash
#
# Combine `which` with `ls -l` to show target of symlinks.
#
# Example:
#   which-l perkeep
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

file="`which "$1"`" || exit 1
ls -l "$file"

