#!/usr/bin/env bash

watch=()
exclude=()
run=0

while [[ "$#" -gt 0 ]]; do
    case $1 in
      -x|--exclude) exclude+=("$2"); shift ;;
      -w|--watch) watch+=("$2"); shift ;;
      -r|--run) run=1 ;;
      -h|--help)
        echo "usage:"
        echo "while-change [--exclude <file>] [--watch <file>] [--run] <command> [<arguments>]";
        echo
        echo "params:"
        echo "-x <file>   --exclude <file> : ignore file or folder changes"
        echo "                               this can be appied multiple times."
        echo "-r          --run            : run the command once without waiting for file changes"
        echo "-w <file>   --watch <file>   : specify which file or path to watch for changes."
        echo "                               this can be appied multiple times. (default ./)"
        echo "-h          --help           : print help info"
        exit 0 ;;
      *) break ;;
    esac
    shift
done


if [ ${#watch[@]} -eq 0 ]; then
  watch=("./")
fi

echo "watch: ${watch[*]}"
[ ${#exclude[@]} -eq 0 ] || echo "exclude: ${exclude[*]}"
echo "command: $*"
echo

if [ $run != 0 ]; then
  "$@"
fi


function check_stdin()
{
  run=0
  while read -t 0.5 -r directory events filename; do
    for x in "${exclude[@]}"; do
      if [[ $directory == $x* ]] || [ "$filename" = "$x" ] || [ "$directory$filename" = "$x" ];
      then
        echo "ignored $directory$filename: $events"
        continue 2
      fi
    done
    echo "changed $directory$filename: $events"
    run=1
  done
}


inotifywait -e close_write,moved_to,create -m "${watch[@]}" -r | while check_stdin
  do
    if [ "$run" != 0 ]; then
      echo "> $*"
      "$@"
    fi
  done
