#!/usr/bin/env ruby
#
# Show networkstatus of wifi and wrapper for wifi-select.
#
##
# Copyright (c) Martin Sigloch <copyright@f0i.de>
# This file is part of github:f0i/bin
# As long as you retain this notice you can do whatever you want with it.
# This code and information are provided without warranty of any kind.
##

WLAN_DEV="wlan0"

if ARGV[0] == "select"
  exec "wifi-select #{WLAN_DEV}"
elsif ARGV[0] == "status"
  connections = `netcfg current`.split("\n").join ', '
  puts connections.empty? ? "Not connected" : "Connected to #{connections}"
  signal = `iwconfig 2> /dev/null | grep Signal`.strip
  if signal.empty?
    puts "No Signal" unless connections.empty?
  else
    puts signal
  end
else
  puts "usage:"
  puts "  wifi select [INTERFACE]"
  puts "  wifi status [INTERFACE]"
end
