#!/usr/bin/env ruby

n = ARGV[0] || 1
n = n.to_i

while !(line=STDIN.gets).nil?
  line.split(/[.,"()'\/!?&%0-9-]+/).each do |l|
    buf=[]
    printed=false
    l.split(/[\s ]+/).each do |x| # split on whitespace and &nbsp;
      next if x == ""
      buf << x
      next if buf.size < n
      puts buf.join ' '
      buf.shift
      printed=true
    end
    puts buf.join unless printed or buf.empty?
  end
end
